openapi: 3.0.3
info:
  title: E-Commerce API
  description: API for managing products, shopping cart, and orders.
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: List of products

  /api/shopping_cart/{customerId}/items:
    post:
      summary: Add product to shopping cart
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                quantity:
                  type: integer
      responses:
        '201':
          description: Item added to shopping cart
        '400':
          description: Bad request
        '404':
          description: Product not found

    get:
      summary: Get items in shopping cart
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of items in cart

  /api/shopping_cart/{customerId}/items/{itemId}:
    delete:
      summary: Remove item from cart
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Item deleted
        '404':
          description: Item not found

  /api/shopping_cart/{customerId}/order:
    post:
      summary: Create an order from shopping cart
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Order created
        '400':
          description: Cart is empty
        '404':
          description: Cart not found

  /api/orders/{orderId}:
    get:
      summary: Fetch order details
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order details
        '404':
          description: Order not found

    put:
      summary: Update an order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Order updated
        '404':
          description: Order not found

    delete:
      summary: Delete an order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Order deleted
        '404':
          description: Order not found

  /api/orders/{orderId}/complete:
    post:
      summary: Complete an order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order completed
        '404':
          description: Order not found
